# Generated by Django 5.2.13 on 2026-05-08 16:13

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='pulp_labels',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
